language: objective-c
before_install:
    - brew update
    - gem install cocoapods
script: xctool -workspace kanxuebbs.xcworkspace -scheme kanxuebbs -sdk iphonesimulator7.0 ONLY_ACTIVE_ARCH=NO -configuration Debug build
